// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_yhDHhWvVMPjTR3TZ9pdOT0pQlYyu1Ro',
    appId: '1:1023349103151:web:756398ec951edcd952c4da',
    messagingSenderId: '1023349103151',
    projectId: 'ebranch-bca-10ccf',
    authDomain: 'ebranch-bca-10ccf.firebaseapp.com',
    storageBucket: 'ebranch-bca-10ccf.appspot.com',
    measurementId: 'G-0P2LWZVL88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRZ3zX4SdUxk51U2IQMKKxHZ_ukzGPQLI',
    appId: '1:1023349103151:android:b738e110a25dea8d52c4da',
    messagingSenderId: '1023349103151',
    projectId: 'ebranch-bca-10ccf',
    storageBucket: 'ebranch-bca-10ccf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCETJzFxIqHVef9-EGUpr3TC2ARBLIj8L8',
    appId: '1:1023349103151:ios:04e6f572da20a18b52c4da',
    messagingSenderId: '1023349103151',
    projectId: 'ebranch-bca-10ccf',
    storageBucket: 'ebranch-bca-10ccf.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCETJzFxIqHVef9-EGUpr3TC2ARBLIj8L8',
    appId: '1:1023349103151:ios:04e6f572da20a18b52c4da',
    messagingSenderId: '1023349103151',
    projectId: 'ebranch-bca-10ccf',
    storageBucket: 'ebranch-bca-10ccf.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_yhDHhWvVMPjTR3TZ9pdOT0pQlYyu1Ro',
    appId: '1:1023349103151:web:e53be56f9c9d66d552c4da',
    messagingSenderId: '1023349103151',
    projectId: 'ebranch-bca-10ccf',
    authDomain: 'ebranch-bca-10ccf.firebaseapp.com',
    storageBucket: 'ebranch-bca-10ccf.appspot.com',
    measurementId: 'G-PNRCPRMQB7',
  );
}
